// Cribbed from the Burner Profile page with transitional and deleted codes removed based on
// https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
export const CountryOptions = [
  [ "Choose Country", "" ],
  [ "United States", "US" ],
  [ "Canada", "CA" ],
  [ "United Kingdom", "GB" ],
  [ "Australia", "AU" ],
  [ "Afghanistan", "AF" ],
  [ "\u00c5land Islands", "AX" ],
  [ "Albania", "AL" ],
  [ "Algeria", "DZ" ],
  [ "American Samoa", "AS" ],
  [ "Andorra", "AD" ],
  [ "Angola", "AO" ],
  [ "Anguilla", "AI" ],
  [ "Antarctica", "AQ" ],
  [ "Antigua and Barbuda", "AG" ],
  [ "Argentina", "AR" ],
  [ "Armenia", "AM" ],
  [ "Aruba", "AW" ],
  [ "Austria", "AT" ],
  [ "Azerbaijan", "AZ" ],
  [ "Bahamas", "BS" ],
  [ "Bahrain", "BH" ],
  [ "Bangladesh", "BD" ],
  [ "Barbados", "BB" ],
  [ "Belarus", "BY" ],
  [ "Belgium", "BE" ],
  [ "Belize", "BZ" ],
  [ "Benin", "BJ" ],
  [ "Bermuda", "BM" ],
  [ "Bhutan", "BT" ],
  [ "Bolivia", "BO" ],
  [ "Bonaire, Sint Eustatius and Saba", "BQ" ],
  [ "Bosnia and Herzegovina", "BA" ],
  [ "Botswana", "BW" ],
  [ "Bouvet Island", "BV" ],
  [ "Brazil", "BR" ],
  [ "British Indian Ocean Territory", "IO" ],
  [ "Brunei Darussalam", "BN" ],
  [ "Bulgaria", "BG" ],
  [ "Burkina Faso", "BF" ],
  [ "Burundi", "BI" ],
  [ "Cabo Verde", "CV" ],
  [ "Cambodia", "KH" ],
  [ "Cameroon", "CM" ],
  [ "Cayman Islands", "KY" ],
  [ "Central African Republic", "CF" ],
  [ "Chad", "TD" ],
  [ "Chile", "CL" ],
  [ "China", "CN" ],
  [ "Christmas Island", "CX" ],
  [ "Cocos (Keeling) Islands", "CC" ],
  [ "Colombia", "CO" ],
  [ "Comoros", "KM" ],
  [ "Congo", "CG" ],
  [ "Congo, Democratic Republic", "CD" ],
  [ "Cook Islands", "CK" ],
  [ "Costa Rica", "CR" ],
  [ "Croatia", "HR" ],
  [ "Cuba", "CU" ],
  [ "Cura\u00e7ao", "CW" ],
  [ "Cyprus", "CY" ],
  [ "Czech Republic", "CZ" ],
  [ "C\u00f4te d'Ivoire", "CI" ],
  [ "Denmark", "DK" ],
  [ "Djibouti", "DJ" ],
  [ "Dominica", "DM" ],
  [ "Dominican Republic", "DO" ],
  [ "Ecuador", "EC" ],
  [ "Egypt", "EG" ],
  [ "El Salvador", "SV" ],
  [ "Equatorial Guinea", "GQ" ],
  [ "Eritrea", "ER" ],
  [ "Estonia", "EE" ],
  [ "Ethiopia", "ET" ],
  [ "Falkland Islands [Malvinas]", "FK" ],
  [ "Faroe Islands", "FO" ],
  [ "Fiji", "FJ" ],
  [ "Finland", "FI" ],
  [ "France", "FR" ],
  [ "French Guiana", "GF" ],
  [ "French Polynesia", "PF" ],
  [ "French Southern Territories", "TF" ],
  [ "Gabon", "GA" ],
  [ "Gambia", "GM" ],
  [ "Georgia", "GE" ],
  [ "Germany", "DE" ],
  [ "Ghana", "GH" ],
  [ "Gibraltar", "GI" ],
  [ "Greece", "GR" ],
  [ "Greenland", "GL" ],
  [ "Grenada", "GD" ],
  [ "Guadeloupe", "GP" ],
  [ "Guam", "GU" ],
  [ "Guatemala", "GT" ],
  [ "Guernsey", "GG" ],
  [ "Guinea", "GN" ],
  [ "Guinea-Bissau", "GW" ],
  [ "Guyana", "GY" ],
  [ "Haiti", "HT" ],
  [ "Heard Island and McDonald Islands", "HM" ],
  [ "Holy See [Vatican City State]", "VA" ],
  [ "Honduras", "HN" ],
  [ "Hong Kong", "HK" ],
  [ "Hungary", "HU" ],
  [ "Iceland", "IS" ],
  [ "India", "IN" ],
  [ "Indonesia", "ID" ],
  [ "Iran (the Islamic Republic of)", "IR" ],
  [ "Iraq", "IQ" ],
  [ "Ireland", "IE" ],
  [ "Isle of Man", "IM" ],
  [ "Israel", "IL" ],
  [ "Italy", "IT" ],
  [ "Jamaica", "JM" ],
  [ "Japan", "JP" ],
  [ "Jersey", "JE" ],
  [ "Jordan", "JO" ],
  [ "Kazakhstan", "KZ" ],
  [ "Kenya", "KE" ],
  [ "Kiribati", "KI" ],
  [ "Korea (the Democratic People's Republic of)", "KP" ],
  [ "Korea (the Republic of)", "KR" ],
  [ "Kuwait", "KW" ],
  [ "Kyrgyzstan", "KG" ],
  [ "Lao People's Democratic Republic", "LA" ],
  [ "Latvia", "LV" ],
  [ "Lebanon", "LB" ],
  [ "Lesotho", "LS" ],
  [ "Liberia", "LR" ],
  [ "Libya", "LY" ],
  [ "Liechtenstein", "LI" ],
  [ "Lithuania", "LT" ],
  [ "Luxembourg", "LU" ],
  [ "Macao", "MO" ],
  [ "Macedonia (the former Yugoslav Republic of)", "MK" ],
  [ "Madagascar", "MG" ],
  [ "Malawi", "MW" ],
  [ "Malaysia", "MY" ],
  [ "Maldives", "MV" ],
  [ "Mali", "ML" ],
  [ "Malta", "MT" ],
  [ "Marshall Islands", "MH" ],
  [ "Martinique", "MQ" ],
  [ "Mauritania", "MR" ],
  [ "Mauritius", "MU" ],
  [ "Mayotte", "YT" ],
  [ "Mexico", "MX" ],
  [ "Micronesia (the Federated States of)", "FM" ],
  [ "Moldova (the Republic of)", "MD" ],
  [ "Monaco", "MC" ],
  [ "Mongolia", "MN" ],
  [ "Montenegro", "ME" ],
  [ "Montserrat", "MS" ],
  [ "Morocco", "MA" ],
  [ "Mozambique", "MZ" ],
  [ "Myanmar", "MM" ],
  [ "Namibia", "NA" ],
  [ "Nauru", "NR" ],
  [ "Nepal", "NP" ],
  [ "Netherlands", "NL" ],
  [ "New Caledonia", "NC" ],
  [ "New Zealand", "NZ" ],
  [ "Nicaragua", "NI" ],
  [ "Niger", "NE" ],
  [ "Nigeria", "NG" ],
  [ "Niue", "NU" ],
  [ "Norfolk Island", "NF" ],
  [ "Northern Mariana Islands", "MP" ],
  [ "Norway", "NO" ],
  [ "Oman", "OM" ],
  [ "Pakistan", "PK" ],
  [ "Palau", "PW" ],
  [ "Palestine, State of", "PS" ],
  [ "Panama", "PA" ],
  [ "Papua New Guinea", "PG" ],
  [ "Paraguay", "PY" ],
  [ "Peru", "PE" ],
  [ "Philippines", "PH" ],
  [ "Pitcairn", "PN" ],
  [ "Poland", "PL" ],
  [ "Portugal", "PT" ],
  [ "Puerto Rico", "PR" ],
  [ "Qatar", "QA" ],
  [ "Romania", "RO" ],
  [ "Russian Federation", "RU" ],
  [ "Rwanda", "RW" ],
  [ "R\u00e9union", "RE" ],
  [ "Saint Barth\u00e9lemy", "BL" ],
  [ "Saint Helena, Ascension and Tristan da Cunha", "SH" ],
  [ "Saint Kitts and Nevis", "KN" ],
  [ "Saint Lucia", "LC" ],
  [ "Saint Martin (French part)", "MF" ],
  [ "Saint Pierre and Miquelon", "PM" ],
  [ "Saint Vincent and the Grenadines", "VC" ],
  [ "Samoa", "WS" ],
  [ "San Marino", "SM" ],
  [ "Sao Tome and Principe", "ST" ],
  [ "Saudi Arabia", "SA" ],
  [ "Senegal", "SN" ],
  [ "Serbia", "RS" ],
  [ "Seychelles", "SC" ],
  [ "Sierra Leone", "SL" ],
  [ "Singapore", "SG" ],
  [ "Sint Maarten (Dutch part)", "SX" ],
  [ "Slovakia", "SK" ],
  [ "Slovenia", "SI" ],
  [ "Solomon Islands", "SB" ],
  [ "Somalia", "SO" ],
  [ "South Africa", "ZA" ],
  [ "South Georgia and the South Sandwich Islands", "GS" ],
  [ "South Sudan ", "SS" ],
  [ "Spain", "ES" ],
  [ "Sri Lanka", "LK" ],
  [ "Sudan", "SD" ],
  [ "Suriname", "SR" ],
  [ "Svalbard and Jan Mayen", "SJ" ],
  [ "Swaziland", "SZ" ],
  [ "Sweden", "SE" ],
  [ "Switzerland", "CH" ],
  [ "Syrian Arab Republic", "SY" ],
  [ "Taiwan", "TW" ],
  [ "Tajikistan", "TJ" ],
  [ "Tanzania, United Republic of", "TZ" ],
  [ "Thailand", "TH" ],
  [ "Timor-Leste", "TL" ],
  [ "Togo", "TG" ],
  [ "Tokelau", "TK" ],
  [ "Tonga", "TO" ],
  [ "Trinidad and Tobago", "TT" ],
  [ "Tunisia", "TN" ],
  [ "Turkey", "TR" ],
  [ "Turkmenistan", "TM" ],
  [ "Turks and Caicos Islands", "TC" ],
  [ "Tuvalu", "TV" ],
  [ "Uganda", "UG" ],
  [ "Ukraine", "UA" ],
  [ "United Arab Emirates", "AE" ],
  [ "United States Minor Outlying Islands", "UM" ],
  [ "Uruguay", "UY" ],
  [ "Uzbekistan", "UZ" ],
  [ "Vanuatu", "VU" ],
  [ "Venezuela, Bolivarian Republic of", "VE" ],
  [ "Viet Nam", "VN" ],
  [ "Virgin Islands (British)", "VG" ],
  [ "Virgin Islands (U.S.)", "VI" ],
  [ "Wallis and Futuna", "WF" ],
  [ "Western Sahara", "EH" ],
  [ "Yemen", "YE" ],
  [ "Yugoslavia", "YU" ],
  [ "Zambia", "ZM" ],
  [ "Zimbabwe", "ZW" ]
];

export const CountryLabels = CountryOptions.reduce((hash, row) => {
  hash[row[1]] = row[0];
  return hash;
}, {});

export const StateOptions = {
  "US": [
    [ "Choose State", "" ],
    [ "Alabama", "AL" ],
    [ "Alaska", "AK" ],
    [ "Arkansas", "AR" ],
    [ "Arizona", "AZ" ],
    [ "California", "CA" ],
    [ "Colorado", "CO" ],
    [ "Connecticut", "CT" ],
    [ "District of Columbia", "DC" ],
    [ "Delaware", "DE" ],
    [ "Florida", "FL" ],
    [ "Georgia", "GA" ],
    [ "Hawaii", "HI" ],
    [ "Idaho", "ID" ],
    [ "Illinois", "IL" ],
    [ "Indiana", "IN" ],
    [ "Iowa", "IA" ],
    [ "Kansas", "KS" ],
    [ "Kentucky", "KY" ],
    [ "Louisiana", "LA" ],
    [ "Maine", "ME" ],
    [ "Maryland", "MD" ],
    [ "Massachusetts", "MA" ],
    [ "Michigan", "MI" ],
    [ "Minnesota", "MN" ],
    [ "Mississippi", "MS" ],
    [ "Missouri", "MO" ],
    [ "Montana", "MT" ],
    [ "Nebraska", "NE" ],
    [ "Nevada", "NV" ],
    [ "New Hampshire", "NH" ],
    [ "New Jersey", "NJ" ],
    [ "New Mexico", "NM" ],
    [ "New York", "NY" ],
    [ "North Carolina", "NC" ],
    [ "North Dakota", "ND" ],
    [ "Ohio", "OH" ],
    [ "Oklahoma", "OK" ],
    [ "Oregon", "OR" ],
    [ "Pennsylvania", "PA" ],
    [ "Rhode Island", "RI" ],
    [ "South Carolina", "SC" ],
    [ "South Dakota", "SD" ],
    [ "Tennessee", "TN" ],
    [ "Texas", "TX" ],
    [ "Utah", "UT" ],
    [ "Vermont", "VT" ],
    [ "Virginia", "VA" ],
    [ "Washington", "WA" ],
    [ "West Virginia", "WV" ],
    [ "Wisconsin", "WI" ],
    [ "Wyoming", "WY" ]
  ],

  "CA": [
    [ "Choose Province/Territory", "" ],
    [ "Alberta", "AB" ],
    [ "British Columbia", "BC" ],
    [ "Manitoba", "MB" ],
    [ "New Brunswick", "NB" ],
    [ "Newfoundland and Labrador", "NL" ],
    [ "Nova Scotia", "NS" ],
    [ "Northwest Territories", "NT" ],
    [ "Nunavut", "NU" ],
    [ "Ontario", "ON" ],
    [ "Prince Edward Island", "PE" ],
    [ "Quebec", "QC" ],
    [ "Saskatchewan", "SK" ],
    [ "Yukon", "YT" ]
  ],

  "AU": [
    [ "Choose Province/Territory", "" ],
    [ "Australian Capital Territory", "ACT" ],
    [ "New South Wales", "NSW" ],
    [ "Northern Territory", "NT" ],
    [ "Queensland", "QLD" ],
    [ "South Australia", "SA" ],
    [ "Tasmania", "TAS" ],
    [ "Victoria", "VIC" ],
    [ "Western Australia", "WA" ]
  ]
};

export const StateLabels = {
  US: "State",
  CA: "Province/Territory",
  AU: "Province/Territory"
};
